#! /usr/bin/env python
# encoding utf-8
# Richard Plangger

from waflib.Context import top_dir,out_dir

src = bld.path.ant_glob('**/*.cpp')

bld.program(
    target='aircontrol',
    source = src,
    includes = ['/usr/include', '../inc','../box2d/Box2D'],
    lib = 'SDL SDL_image',
    cflags='-g',
    use = 'box2d',
    install_path = top_dir
    )
    
